version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_DB_HOST=${DB_HOST}
      - VITE_DB_USER=${DB_USER}
      - VITE_DB_PASSWORD=${DB_PASSWORD}
      - VITE_DB_NAME=${DB_NAME}
      - VITE_DB_PORT=${DB_PORT:-3306}
      - NODE_ENV=production
    restart: unless-stopped