version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://api:3000
      - NODE_ENV=production
      - VITE_DB_HOST=${DB_HOST}
      - VITE_DB_USER=${DB_USER}
      - VITE_DB_PASSWORD=${DB_PASSWORD}
      - VITE_DB_NAME=${DB_NAME}
      - VITE_DB_PORT=${DB_PORT:-3306}
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT:-3306}
    restart: unless-stopped